Select the API and page structure
aakbarkhan/metrics-webapp pull request #1
Opened 2022-01-03 09:28 UTC by aakbarkhan

2022-01-08 16:33 UTC, AshakaE requested changes
### Hi @aakbarkhan  🙋‍♀️, 

Good job so far! 👌

Your:
   - Git flow ✔️ 
   - Pull request 👍 

There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


#  Required Changes ♻️ 🚧
_Check the comments under the review._

- [x] Please write unit tests for all components and pure functions in the Redux code
- [ ] Please write integration tests using the React Testing Library
- [ ] Please add the link to the video presentation in the pull request
- [ ] Please remove all console log statements in your project 💡 
- [ ] Please remember to acknowledge the author of the [original design](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), [Nelson Sakwa](https://www.behance.net/sakwadesignstudio) in your README file 🙏 


###  Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
Feel free to leave any questions or comments in the PR thread if something is not 100% 
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-08 16:33 UTC, AshakaE commented on README.md
> +[LINK Live]()
- [ ] Please fix the live link to the deployed project

2022-01-12 13:52 UTC, rloterh requested changes
Hi Aku, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to complete this project but you are almost there! 🚦  🚦  

## Good Points 👍 
- Descriptive Pull Request
- App is correctly deployed
- Good video presentation of the project
- Redux is effectively used to manage state data
- Good test coverage
- Good ReadMe
- No linter errors

## Required Changes ♻️
_Kindly check the comments under the review._

<br>
Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 4 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-12 13:52 UTC, rloterh commented on README.md
> +## Authors
- [ ] Kindly change the header title _Authors_ to _Author_, as this project is done solely. This will make your ReadMe appear more professional.

2022-01-12 13:52 UTC, rloterh commented on README.md
Your _ReadMe_ needs some improvements so as to make it appear more professional. Kindly note that _ReadMe_ is mostly the first place that visitors of this project's repository will go and therefore it has to be very detailed and professional. Also, it needs to be done well with respect to this capstone project,  which will likely feature on your portfolio. Therefore, kindly ensure to improve upon these aspects of your ReadMe:
- [ ] _Project description_, _how to set up_, _run and test this project_ **should be detailed, clear, and well** organized.
- [ ] The _code_ aspects in each procedure should be quoted with **backticks**.
- [ ] Include necessary screenshots, project demo links where applicable so as to give a birds-eye view of your project
- [ ] All _typos_ **should be corrected**. You can crosscheck by installing the [Grammarly plugin](https://www.grammarly.com/)

2022-01-12 13:52 UTC, rloterh commented on src/index.css
> +.wrapper {
- [ ] The styling of the list on your Homepage does not conform to the alternating dual-color pattern of the provided [design template](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), and therefore difficult to differentiate the details of each list item. Kindly note we as much as possible want your design to match the provided [template](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)). Therefore kindly ensure that cells of your list follow the **alternating dual-color pattern**. Each cell of the list item should have surrounding cells having **different (alternating) background color(s)**.
- [ ] Kindly ensure that data is properly wrapped within the cells/ _divs_ on the _display page_.

**Your design:**
![image](https://user-images.githubusercontent.com/12745474/149150166-f7d32fae-439b-4ad3-9fe4-3bf7ca7ced47.png)

![image](https://user-images.githubusercontent.com/12745474/149151332-73df2af9-a4a7-4d15-95cb-4821fcece0b0.png)



**The original design:**
![image](https://user-images.githubusercontent.com/12745474/142270463-4d16b9d3-7557-430c-80eb-a7c40589a4a6.png)

![image](https://user-images.githubusercontent.com/12745474/149150871-e9385b03-84c3-4285-82ed-d12943e24204.png)

2022-01-12 13:52 UTC, rloterh commented on src/components/countrylist.js
> +  const country = props;
- [ ] As specified, kindly implement a **redux filter/ search** functionality so as to enable filtering of countries. The filter/ search field should be displayed on the Homepage.

2022-01-13 15:10 UTC, elyor-doniyorov approved these changes
Hi @aakbarkhan, 

In my opinion, your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2022-01-13 15:15 UTC, merged